### PR TITLE
Base branch for some new updates.

### PR DESCRIPTION
**Pull request by theengineear**

### CODE REVIEW

**Comment by theengineear** [comment]
@alexcjohnson , this is the current process (I think, @etpinard will have the final say). Here's what needs to happen to get connectgaps, barnorm, and heatmap text into the Libraries. Once there, I use a script to generate (with some minor changes) what the graph_reference.js looks like in Themes. @etpinard may already have a better way of doing this in the works. I can't recall... it definitely needs to happen though.

Here are the relevant PRs to this main branch: #35 , #34 , #33

**Comment by etpinard** [comment]
Yeah. I'm was working on something before the holidays. 

Essentially,  the new system will take in all the Plotly.module attributes (with the correct inheritance and such) to build the full graph reference JSON.

Andrew, I would merge all your PRs (after $ make run)

**Comment by etpinard** [comment]
That system is still a few working days away though.

**Comment by theengineear** [comment]
@etpinard , ran $ make run, any thing else?

**Comment by etpinard** [comment]
:dancer: 

I'll take care of the rest.

**Comment by theengineear** [comment]
thx!

**Pull request merged**
